In [ ]:
import pickle
import numpy as np
import networkx as nx
import os, sys

data_dir = './data/orig'
for file in os.listdir(data_dir):
    print(file)
    with open(os.path.join(data_dir, file), 'rb') as f:
        x = pickle.load(f)
    for g in x:
        print(g)
    print('\n')

In [20]:
import pickle
import numpy as np
import networkx as nx
import os, sys

data_dir = './data/generated'
for file in os.listdir(data_dir):
    if file == ".ipynb_checkpoints": continue
    print(file)
    with open(os.path.join(data_dir, file), 'rb') as f:
        x = pickle.load(f)
    for g in x:
        print(g)

DPGGAN_nx_adj.pkl_eps10.0.pkl
Graph with 4039 nodes and 88234 edges
DPGGAN_nx_adj.pkl_eps10.0_ADAM.pkl
Graph with 4039 nodes and 88234 edges


In [26]:
with open("./data/generated/DPGGAN_nx_adj.pkl_eps0.5.pkl", 'rb') as f:
    x = pickle.load(f)
    for g in x:
        print(g)

Graph with 4039 nodes and 88234 edges


In [27]:
with open("../Data/Facebook/nx_adj.pkl", 'rb') as f:
    o = pickle.load(f)

O = nx.adjacency_matrix(o).toarray()
G = nx.adjacency_matrix(g).toarray()

In [28]:
O


array([[0, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4039, 4039))

In [29]:
G

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(4039, 4039))

In [34]:
O[O == 1]

array([1, 1, 1, ..., 1, 1, 1], shape=(176468,))

In [35]:
c = 0
for i in range(4039-1):
    for j in range(i+1, 4039):
        if G[i][j] != O[i][j]:
            c += 1

print(c)

174798


In [31]:
4039*4038 / 2

8154741.0