In [1]:
import json
import pickle
import numpy as np

with open("musae_git_features.json", 'r') as f:
    d = json.load(f)

In [15]:
a = [0 for _ in range(4004+1)]
f = 4004+1
n = len(d)

M = np.zeros((n,f))

for v, a_list in d.items():
    for a in a_list:
        M[int(v)][a] = 1

M


In [23]:
with open("feature_matrix_full.pkl", 'wb') as f:
    pickle.dump(M.astype(int), f)

In [24]:
from scipy.stats import entropy

def entropy_per_column(X):
    # Assumes binary features: 0 or 1
    probs = np.mean(X, axis=0)  # P(X=1) per feature
    ent = -probs * np.log2(probs + 1e-10) - (1 - probs) * np.log2(1 - probs + 1e-10)
    return ent

ent = entropy_per_column(M)
sorted_indices = np.argsort(-ent)  # descending entropy
print(sorted_indices)

[1532 2472 3771 ...  645 3982 2288]


In [25]:
M = M[:, sorted_indices[:50]]

In [26]:
M

array([[1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(37700, 50))

In [27]:
with open("feature_matrix_50_highest_entropy.pkl", 'wb') as f:
    pickle.dump(M.astype(int), f)

In [28]:
M

array([[1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(37700, 50))

In [30]:
with open("CAGM_attribute.txt", 'w') as f:
    for i, row in enumerate(M.astype(int)):
        f.write(f"{i} " + " ".join(str(e) for e in row) + '\n')